language: node_js
node_js:
- 4.4.5
before_install:
- npm install -g grunt-cli
- npm install -g bower
install:
- npm install
- bower install
script:
- grunt test
- grunt build
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: ernie.shu@gmail.com
  password:
    secure: C64pcZW58zO6GtnuldFxQeh2hf5ZPMFUQBlAsUWl+GyRY64lV+3OzI+Avwnb2EwW8vOcMZZShZk0Xhpo9akOPzKyZtKP/nOCAv6InWC3Dv8szJunGWwwuA9Xi2iIT+70nA/9YzaXFgSKPd3qmY14PrhJ7UNH0uQqs4jIeeJCFwKorXwqezwNJL/4y/fy0jmgP87GGGX2EgJnTROiWeSmy00LqGSgYTuB5WSEwbKNlcV9ONaclf9XW0Q3YX4nhDslYHHWTW69k5S8dPFvk2ukWmYHp2TxZ+3H/AnhHphu8etXu2K4nvKxuxlVLNUql5s+yRjz8LITgDy3/E4Q5NkcQKeGeZFXBef9FGWuDuQo2oAqhRDIOPifyPqmsqBogviv2c2eXm/ICUFkyVUv2SRTGrKdEbB5pfrxMsnbBNHvbsPs0R08rEucvd3VmZOuFHXdQM40jZLhrS+algNfO1c8FhYQpdx+9DTVZJIAy9T7sq26KTFXb1/ysNpwmndtToyCicR5bizYBEUFRvVQYgLgCCUHYnOFK3gQQQqLu8e3GDV6NnJOln4MVupiRCe5QR2SVvO69DkVwi9hU0Jau5W0aoFPCE3nelZN5ZY4ZGqUf5Md7SkfWbYKEeb/hZziplWvbjFjQBTg/kFRPeMP+EtM6IFrcQCo+NyoL2b3WCqSXaA=
  organization: ernie.shu.org
  space: development
  on:
    repo: ernieshu/petstore-ui-2
